### ISSUE TITLE
python3 chat.py Error

### ISSUE THREAD

**Issue by MichiScotsguard** [retr0reg/AutoGDB#4]
I got these errors when executing chat.py with python3. What do I do?

Traceback (most recent call last):
  File "/home/kali/Downloads/tools/AutoGDB/chat.py", line 1, in <module>
    from src.utils import cli
  File "/home/kali/Downloads/tools/AutoGDB/src/utils.py", line 1, in <module>
    from autogdb import *
  File "/home/kali/Downloads/tools/AutoGDB/autogdb/__init__.py", line 1, in <module>
    from .models import *
  File "/home/kali/Downloads/tools/AutoGDB/autogdb/models.py", line 7, in <module>
    from langchain.agents import Tool
ModuleNotFoundError: No module named 'langchain'

**Comment by retr0reg** [comment]
Hi, please try `python3 -m pip install -r requirements.txt` or `python3 -m pip install -r langchain`

**Comment by MichiScotsguard** [comment]
Traceback (most recent call last):
  File "/home/kali/Downloads/tools/AutoGDB/chat.py", line 1, in <module>
    from src.utils import cli
  File "/home/kali/Downloads/tools/AutoGDB/src/utils.py", line 1, in <module>
    from autogdb import *
  File "/home/kali/Downloads/tools/AutoGDB/autogdb/__init__.py", line 1, in <module>
    from .models import *
  File "/home/kali/Downloads/tools/AutoGDB/autogdb/models.py", line 7, in <module>
    from langchain.agents import Tool
  File "/home/kali/.local/lib/python3.11/site-packages/langchain/agents/__init__.py", line 36, in <module>
    from langchain.agents.agent import (
  File "/home/kali/.local/lib/python3.11/site-packages/langchain/agents/agent.py", line 49, in <module>
    from langchain.chains.base import Chain
  File "/home/kali/.local/lib/python3.11/site-packages/langchain/chains/__init__.py", line 82, in <module>
    from langchain.chains.sql_database.query import create_sql_query_chain
  File "/home/kali/.local/lib/python3.11/site-packages/langchain/chains/sql_database/query.py", line 9, in <module>
    from langchain.utilities.sql_database import SQLDatabase
  File "/home/kali/.local/lib/python3.11/site-packages/langchain/utilities/sql_database.py", line 1, in <module>
    from langchain_community.utilities.sql_database import (
  File "/home/kali/.local/lib/python3.11/site-packages/langchain_community/utilities/sql_database.py", line 9, in <module>
    from sqlalchemy import (
ImportError: cannot import name 'Executable' from 'sqlalchemy' (/usr/lib/python3/dist-packages/sqlalchemy/__init__.py)

There is another error after executing ```python3 -m pip install -r requirements.txt```.

**Comment by milondas0002** [comment]
when i run the tool it asks to input open AI API URL, unfortunately first time i input a paid API which i don't actually have. now i can't reset that, i also can't find the .JSON file by removing which i can again reset the tool and it will again ask me to input the base API URL, so please help me in that case
